version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing all the chissel
          command: 'apt-get update && apt-get install -y git gcc pkg-config autoconf automake autopoint libreadline-dev make guile-2.0 texinfo lzip'
      - run:
          name: Config
          command: './autogen.sh'
      - run:
          name: Compile and check
          command: 'make && make check'
